---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - linter
  - build

# linter
dockerlint:
  stage: linter
  image: vpgrp/linter:docker
  script:
    - find . -type f -name "Dockerfile" | grep -v 'vendor' | xargs -I{} dockerlint {}
  allow_failure: true

golint:
  stage: linter
  image: vpgrp/linter:golang
  before_script:
    - go get github.com/GeertJohan/fgt
  script:
    - find . -type f -name "*\.go" | grep -v 'vendor' | xargs -I{} fgt golint {}
  allow_failure: true

# build
go-get:
  stage: build
  image: vpgrp/golang:latest
  script:
    - go get -u github.com/vente-privee/influxdb-relay

go-build:
  stage: build
  image: vpgrp/golang:latest
  before_script:
    - mkdir -p ${GOPATH}/src/github.com/vente-privee
    - ln -fsv ${CI_PROJECT_DIR} ${GOPATH}/src/github.com/vente-privee/influxdb-relay
  script:
    - cd ${GOPATH}/src/github.com/vente-privee/influxdb-relay
    - go build -a -ldflags '-extldflags "-static"' -o influxdb-relay
# EOF

