---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - linter
  - build
  - pages

# linter
dockerlint:
  stage: linter
  image: vpgrp/linter:docker
  script:
    - find . -type f -name "Dockerfile" | grep -v 'vendor' | xargs -I{} dockerlint {}

golint:
  stage: linter
  image: vpgrp/linter:golang
  before_script:
    - go get github.com/GeertJohan/fgt
  script:
    - find . -type f -name "*\.go" | grep -v 'vendor' | xargs -I{} fgt golint {}

# build
docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    - DOCKER_DRIVER: overlay
  script:
    - docker build --rm .

go-build:
  stage: build
  image: vpgrp/golang:latest
  before_script:
    - mkdir -p ${GOPATH}/src/github.com/vente-privee
    - ln -fsv ${CI_PROJECT_DIR} ${GOPATH}/src/github.com/vente-privee/influxdb-relay
  script:
    - cd ${GOPATH}/src/github.com/vente-privee/influxdb-relay
    - go build -a -ldflags '-extldflags "-static"' -o influxdb-relay


# vpage
pages:
  stage: pages
  tags:
    - docker
  image: vptech/vpages:latest
  script:
    - env REPO_NAME=$CI_PROJECT_NAME build-pages
  artifacts:
    paths:
      - public
  only:
    - add-vpage

# EOF
